version: "3.4"

services:
  client:
    build:
      context: ./genoas_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    env_file:
      - .env
    command: sh -c 'yarn; yarn run serve'
    ports:
      - "${PORT}:${PORT}"
      - "35729:35729"
    volumes:
      - ./:/app
